name: home_-_particles
timestamp: 1480605066
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1478189119
positions: {  }
sections:
  navigation: Navigation
  about: About
  process: Experience
  skills: Skills
  quote: Quote
  jobTitle: Resume
  experience: Education
  portfolio: Portfolio
  testimonials: Testimonials
  maincontent-bottom: Maincontent-bottom
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9608: 'Logo / Image'
    logo-9571: 'Logo / Image'
  menu:
    menu-6409: Menu
  social:
    social-3171: Social
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
    owlcarousel-7694: Owlcarousel
    owlcarousel-3535: Owlcarousel
  sectiontitle:
    sectiontitle-6772: Sectiontitle
    sectiontitle-7352: Sectiontitle
    sectiontitle-7889: Sectiontitle
    sectiontitle-7106: Sectiontitle
    sectiontitle-4130: Sectiontitle
    sectiontitle-8354: Sectiontitle
  profile:
    profile-4138: Profile
  bio:
    bio-4926: Bio
  statscubes:
    statscubes-6326: Statscubes
  custom:
    custom-9799: Custom
  processflow:
    processflow-5648: Processflow
  skillchart:
    skillchart-5713: Skillchart
    skillchart-3634: Skillchart
    skillchart-9262: Skillchart
    skillchart-1146: Skillchart
    skillchart-6806: Skillchart
    skillchart-1002: Skillchart
  spacer:
    spacer-2470: Spacer
    spacer-1003: Spacer
  quote:
    quote-8045: Quote
  career:
    career-4984: Career
  timeline:
    timeline-4115: Timeline
  isotope:
    isotope-4854: Isotope
  copyright:
    copyright-1736: Copyright
  horizontalmenu:
    horizontalmenu-9034: 'Horizontal Menu'
  totop:
    totop-8670: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
