name: home
timestamp: 1478755695
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1478189119
positions: {  }
sections:
  navigation: Navigation
  about: About
  portfolio: Portfolio
  skills: Skills
  jobTitle: JobTitle
  experience: Experience
  testimonials: Testimonials
  process: Process
  maincontent-bottom: Maincontent-bottom
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9608: 'Logo / Image'
    logo-9571: 'Logo / Image'
  menu:
    menu-6409: Menu
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
    owlcarousel-7694: 'What clients Say'
    owlcarousel-3535: 'Owl Carousel'
  sectiontitle:
    sectiontitle-6772: 'Section Title'
    sectiontitle-4130: 'Section Title'
    sectiontitle-7889: 'Section Title'
    sectiontitle-7106: 'Section Title'
    sectiontitle-8354: 'Section Title'
    sectiontitle-7352: 'Section Title'
    sectiontitle-2639: 'Section Title'
  profile:
    profile-4138: 'Profile Image'
  bio:
    bio-4926: 'Mini Bio'
  statscubes:
    statscubes-6326: 'Stats Cubes'
  custom:
    custom-9799: Services
    custom-1231: 'Custom HTML'
    custom-9050: 'Custom HTML'
    custom-8220: 'Custom HTML'
  isotope:
    isotope-4854: Portfolio
  skillchart:
    skillchart-5713: 'Circle Graph'
    skillchart-3634: 'Circle Graph'
    skillchart-9262: 'Circle Graph'
    skillchart-1146: 'Circle Graph'
    skillchart-6806: jQuery
    skillchart-1002: PHP
  skillbar:
    skillbar-9825: SkillBar
    skillbar-2264: SkillBar
  career:
    career-4984: Career
  timeline:
    timeline-4115: Timeline
  processflow:
    processflow-5648: 'Process Flow'
  messages:
    system-messages-9954: 'System Messages'
  social:
    social-8515: Social
  contactdetails:
    contactdetails-5862: 'Contact Details'
  copyright:
    copyright-1736: Copyright
  totop:
    totop-8670: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
