name: home
timestamp: 1480626141
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1478189119
positions: {  }
sections:
  navigation: Navigation
  about: About
  process: Experience
  skills: Skills
  quote: Quote
  jobTitle: Resume
  experience: Education
  portfolio: Portfolio
  testimonials: Testimonials
  maincontent-bottom: Maincontent-bottom
  header: Header
  mainbar: Mainbar
  sidebar: Sidebar
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-9608: 'Logo / Image'
  menu:
    menu-6409: Menu
  owlcarousel:
    owlcarousel-2455: 'Owl Carousel'
    owlcarousel-7694: 'What clients Say'
  sectiontitle:
    sectiontitle-6772: 'Section Title'
    sectiontitle-7352: MyExperience
    sectiontitle-7889: Skills
    sectiontitle-7106: 'Section Title'
    sectiontitle-4130: 'Section Title'
    sectiontitle-8354: 'Section Title'
    sectiontitle-2639: 'Section Title'
  profile:
    profile-4138: 'Profile Image'
  bio:
    bio-4926: 'Mini Bio'
  statscubes:
    statscubes-6326: 'Stats Cubes'
  custom:
    custom-9799: Services
    custom-5538: 'Custom HTML'
  processflow:
    processflow-5648: 'Process Flow'
  skillchart:
    skillchart-5713: 'Circle Graph'
    skillchart-3634: 'Circle Graph'
    skillchart-9262: 'Circle Graph'
    skillchart-1146: 'Circle Graph'
    skillchart-6806: jQuery
    skillchart-1002: PHP
  quote:
    quote-8045: Quote
  career:
    career-4984: Career
  timeline:
    timeline-4115: Education
  spacer:
    spacer-spacer-7598: Spacer
    spacer-spacer-1929: Spacer
    spacer-1647: Spacer
    spacer-8422: Spacer
  isotope:
    isotope-7263: Isotope
  messages:
    system-messages-9954: 'System Messages'
  social:
    social-8515: Social
  googlemap:
    googlemap-5181: 'Google Map'
  copyright:
    copyright-1736: Copyright
  totop:
    totop-8670: 'To Top'
  mobile-menu:
    mobile-menu-5697: Mobile-menu
inherit: {  }
