version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1478189119
layout:
  /navigation/:
    -
      - 'logo-9608 20'
      - 'menu-6409 80'
  /header/:
    -
      - owlcarousel-2455
  /about/:
    -
      - sectiontitle-6772
    -
      - 'profile-4138 25'
      - 'bio-4926 45'
      - 'statscubes-6326 30'
    -
      - custom-9799
  /process/:
    -
      - sectiontitle-7352
    -
      - processflow-5648
  /skills/:
    -
      - sectiontitle-7889
    -
      - 'skillchart-5713 16.7'
      - 'skillchart-3634 16.7'
      - 'skillchart-9262 16.7'
      - 'skillchart-1146 16.7'
      - 'skillchart-6806 16.7'
      - 'skillchart-1002 16.7'
  /quote/:
    -
      - 'spacer-2470 20'
      - 'custom-8278 60'
      - 'spacer-1003 20'
  /jobTitle/:
    -
      - career-4984
  /experience/:
    -
      - sectiontitle-7106
    -
      - timeline-4115
  /portfolio/:
    -
      - sectiontitle-4130
    -
      - isotope-4854
  /testimonials/:
    -
      - sectiontitle-8354
    -
      - owlcarousel-7694
    -
      - owlcarousel-3535
  /container-main/:
    -
      -
        'mainbar 75':
          -
            - system-messages-9954
          -
            - sectiontitle-2639
          -
            - social-8515
          -
            - contactdetails-5862
          -
            - 'spacer-1647 20'
            - 'custom-5538 60'
            - 'spacer-8422 20'
      -
        'sidebar 25': {  }
  /maincontent-bottom/:
    -
      - custom-8220
  /footer/:
    -
      - copyright-1736
    -
      - totop-8670
  /offcanvas/:
    -
      - mobile-menu-5697
structure:
  navigation:
    type: section
    attributes:
      boxed: ''
      class: navbar-transparent
  header:
    attributes:
      boxed: ''
      class: g-flushed
  about:
    type: section
    attributes:
      boxed: ''
  process:
    type: section
    attributes:
      boxed: ''
  skills:
    type: section
    attributes:
      boxed: ''
      class: ''
  quote:
    type: section
    attributes:
      boxed: ''
  jobTitle:
    type: section
    attributes:
      boxed: ''
  experience:
    type: section
    attributes:
      boxed: ''
  portfolio:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
      class: 'clients parallax'
  mainbar:
    type: section
    subtype: main
    attributes:
      class: ''
    block:
      variations: center
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  maincontent-bottom:
    type: section
    attributes:
      boxed: '2'
      class: ''
  footer:
    attributes:
      boxed: ''
      class: center
  offcanvas:
    attributes:
      boxed: ''
content:
  logo-9608:
    title: 'Logo / Image'
    attributes:
      text: 'LEONID SPEKTOR'
      class: 'g-logo g-logo-Identity'
  menu-6409:
    block:
      class: smallpadding-content
      variations: align-right
  owlcarousel-2455:
    title: 'Owl Carousel'
    attributes:
      variant: o1
      slides: '1'
      full: '1'
      loop: '0'
      items:
        -
          image: 'gantry-media://header/img01.png'
          title: 'LEONID SPEKTOR'
          desc: 'Sen. Software Developer'
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'Item 1'
    block:
      variations: title1
  sectiontitle-6772:
    title: 'Section Title'
    attributes:
      title: About
      label: Me
      icon: 'fa fa-user fa-2x'
    block:
      variations: center
  profile-4138:
    title: 'Profile Image'
    attributes:
      image: 'https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAARvAAAAJDlkYzBhMDIwLWI4MDQtNDRiNC1iNDhiLThmZTdiNDM5ZDczZg.jpg'
      name: 'LEONID SPEKTOR'
      title: 'Sen. Software Developer / Tech Lead '
  bio-4926:
    title: 'Mini Bio'
    attributes:
      title: '"All computers wait at the same speed."'
      text: "<p>Design and Development of front and back end security components for e-Commerce Financial Applications. Design and development of a high throughput, mission-critical high-availability insurance enrollment module, securing the transactions against penetration violations, integration with mainframe-based modules. Duties included: security modules analysis, design and development of a catalog-based system, front end development, back end (controller) development, development of complex InfoView reports, investigations, debugging, participation in cross-team application inquiries, providing recommendations on new tools and efficient development, leading a remote and local-based team, documentation development. </p>\n<p>\nLanguages and Technologies used: Java/J2EE API, Python, JavaScript, Ajax, jQuery, HTML, JSP, JSTL, Scriplets, Tag Library, CSS, ant, Spring, Struts MVC, Eclipse, WebSphere, Clustering, DBVisualizer, SQL/PL-SQL,  DB2 Server, log4j,  pdf, Junit, Maniframe, Cobol, InfoView, RESTful Web Services.</p>"
      image: 'gantry-media://signature.png'
  statscubes-6326:
    title: 'Stats Cubes'
    attributes:
      dob: '1974-06-16'
      phone: ' (647) 882 8001 '
      email: queryfilter@yahoo.com
      address: '205 HILDA AVENUE UNIT 1505 TORONTO, ONTARIO M2M-4B1'
      items:
        -
          icon: 'fa fa-group fa-2x'
          label: Languages
          value: '4'
          name: Languages
        -
          icon: 'fa fa-flag fa-2x'
          label: 'Years Experience'
          value: '9'
          name: Exp
        -
          icon: 'fa fa-trophy fa-2x'
          label: 'Awards & Accolades'
          value: '7'
          name: Awards
        -
          icon: 'fa fa-thumbs-up fa-2x'
          label: 'Volunteer Efforts'
          value: '2'
          name: 'Volunteer Efforts'
  custom-9799:
    title: Services
    attributes:
      html: "<div class=\"g-grid services\">\n\t\t<div class=\"g-block size-33-3\">\n\t\t\t<!-- Service -->\n\t\t\t<div class=\"services-box new-line item_left\">\n\t\t\t\t<h4>Customer Support</h4>\n\t\t\t\t<div class=\"services-box-icon\">\n\t\t\t\t\t<i class=\"fa fa-smile-o fa-3x\"></i>\n\t\t\t\t</div>\n\t\t\t\t<div class=\"service-box-info\">\n\t\t\t\t\t<p>\n\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellesque imperdiet. Nulla lacinia iaculis nulla.\n\t\t\t\t\t</p>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<!-- End Service -->\n\t\t</div>\n\t\t<div class=\"g-block size-33-3\">\n\t\t\t<!-- Service -->\n\t\t\t<div class=\"services-box new-line item_bottom\">\n\t\t\t\t<h4>Web Design</h4>\n\t\t\t\t<div class=\"services-box-icon\">\n\t\t\t\t\t<i class=\"fa fa-html5 fa-3x\"></i>\n\t\t\t\t</div>\n\t\t\t\t<div class=\"service-box-info\">\n\t\t\t\t\t<p>\n\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellesque imperdiet. Nulla lacinia iaculis nulla.\n\t\t\t\t\t</p>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<!-- End Service -->\n\t\t</div>\n\t\t<div class=\"g-block size-33-3 clearfix\">\n\t\t\t<!-- Service -->\n\t\t\t<div class=\"services-box new-line item_right\">\n\t\t\t\t<h4>Wordpress Themes</h4>\n\t\t\t\t<div class=\"services-box-icon\">\n\t\t\t\t\t<i class=\"fa fa-link fa-3x\"></i>\n\t\t\t\t</div>\n\t\t\t\t<div class=\"service-box-info\">\n\t\t\t\t\t<p>\n\t\t\t\t\t\tLorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque rutrum pellesque imperdiet. Nulla lacinia iaculis nulla.\n\t\t\t\t\t</p>\n\t\t\t\t</div>\n\t\t\t</div>\n\t\t\t<!-- End Service -->\n\t\t</div>"
  sectiontitle-7352:
    title: MyExperience
    attributes:
      title: 'my '
      label: Experience
      icon: 'fa fa-gears fa-2x'
      class: white
    block:
      variations: center
  processflow-5648:
    title: 'Process Flow'
    attributes:
      items:
        -
          icon: 'fa fa-sellsy'
          title: 'Wescom Communication'
          desc: 'Developing front and back end components for Long Term Care Medical Application. '
          name: Discussion
        -
          icon: 'fa fa-home'
          title: 'Ministry of Transportation (MTO)/OpenSystems'
          desc: 'Providing production and second level support to e-commerce J2EE application (Authorized Requestor Information System); developing new modules for inter-ministry secure document transfer. '
          name: Idea
        -
          icon: 'fa fa-flash'
          title: 'Manulife Financial'
          desc: 'Design and Development of front and back end security components for e-Commerce Financial Applications. '
          name: Review
        -
          icon: 'fa fa-taxi'
          title: BlackBerry/TCS
          desc: 'Development of cloud-based Mobile Device Management JEE application. Duties included: investigations and debugging, development of JEE application '
          name: Deliver
    block:
      variations: 'nomarginall nopaddingall'
      extra:
        -
          style: 'clear:both'
  sectiontitle-7889:
    title: Skills
    attributes:
      title: My
      label: Skills
      icon: 'fa fa-bar-chart fa-2x'
    block:
      class: center
  skillchart-5713:
    title: 'Circle Graph'
    attributes:
      title: Leadership
      desc: 'The action of leading a group of people or an organization.'
      percent: '65'
  skillchart-3634:
    title: 'Circle Graph'
    attributes:
      title: Initiative
      desc: 'The ability to assess and initiate things independently.'
      percent: '67'
  skillchart-9262:
    title: 'Circle Graph'
    attributes:
      title: Communication
      desc: 'The imparting or exchanging of information or news.'
      percent: '72'
  skillchart-1146:
    title: 'Circle Graph'
    attributes:
      title: Enthusiasm
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
      percent: '81'
  skillchart-6806:
    title: jQuery
    attributes:
      title: 'Team Work'
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
      percent: '66'
  skillchart-1002:
    title: PHP
    attributes:
      title: Creativity
      desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.'
      percent: '89'
  custom-8278:
    title: 'Custom HTML'
    attributes:
      html: "<i class=\"fa fa-2x fa-quote-right fa-flip-horizontal\" aria-hidden=\"true\"></i><h4 style=\"display:inline\">  I believe that we are who we choose to be. Nobody’s going to come and save you, you’ve got to save yourself. Nobody’s going to give you anything. You’ve got to go out and fight for it. Nobody knows what you want except for you. And nobody will be as sorry as you if you don’t get it. So don’t give up on your dreams. </h4>\n<i class=\"fa fa-2x fa-quote-right\" aria-hidden=\"true\"></i>"
    block:
      variations: center
  career-4984:
    attributes:
      label: 'I am available for'
      title: Hire
      linktxt: 'Hire Me'
      link: '#g-container-main'
      location: 'gantry-media://2016/11/LEONID_SPEKTOR_Resume393.doc'
    block:
      variations: center
  sectiontitle-7106:
    title: 'Section Title'
    attributes:
      title: my
      label: Education
      icon: 'fa fa-graduation-cap  fa-2x'
    block:
      class: center
  timeline-4115:
    title: Education
    attributes:
      items:
        -
          section: present
          title: 'York University Toronto'
          label: 'Computer Science'
          desc: 'Thesis: Real-time image-analysis system for measuring red velocity. Installation: Sunnybrook Hospital'
          startdate: 2013-12
          enddate: 2016-11
          current: 'yes'
          name: 'Creative Agency'
        -
          section: present
          title: 'University of Toronto'
          label: 'Master of Engineering'
          desc: 'Thesis: Real-time image-analysis system for measuring red velocity. Installation: Sunnybrook Hospital'
          startdate: 2010-06
          enddate: 2013-11
          current: 'no'
          name: Infosys
  sectiontitle-4130:
    title: 'Section Title'
    attributes:
      title: 'My Recent'
      label: Readings
      icon: 'fa fa-book fa-2x'
      class: white
    block:
      class: center
  isotope-4854:
    title: Portfolio
    attributes:
      items:
        -
          filters: 'tommy zed'
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: 'Projects Done'
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
        -
          filters: ''
          image: 'gantry-media://savannah/edgar.jpg'
          icon: 'fa fa-align-justify'
          title: dasdad
          label: ''
          name: 'New item'
  sectiontitle-8354:
    title: 'Section Title'
    attributes:
      title: My
      label: Testimonials
      icon: 'fa fa-users fa-2x'
      class: white
    block:
      class: center
  owlcarousel-7694:
    title: 'What clients Say'
    attributes:
      variant: o3
      dots: enable
      slides: '1'
      autoplay: enable
      items:
        -
          image: ''
          title: ''
          desc: "<p class=\"quote\">\"It’s easy to see the passion that the guys have for their work. He really care about making unique designs for their clients, and put in incredible effort to make the whole process a real pleasure.\"</p>\n\t\t\t\t                \t<p class=\"author\">Jak Doe</p>\n\t\t\t\t                "
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'Jak Doe'
        -
          image: ''
          title: ''
          desc: "<p class=\"quote\">\"My website couldn’t look better after working with the him on the redesign. Now my site and corporate\tbranding is outstanding! He is awesome.\"</p>\n\t\t\t\t                \t<p class=\"author\">John Doe</p>\n\t\t\t\t                \t<p class=\"company\">Manager <a href=\"#\">@Web Planet</a></p>"
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'John Doe'
        -
          image: ''
          title: ''
          desc: "<p class=\"quote\">\"I am incredibly happy with the increased traffic my site has received since working with you! He is the best at this job.\"</p>\n\t\t\t\t                \t<p class=\"author\">Jane Doe</p>\n\t\t\t\t                \t"
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: 'Jane Doe'
  owlcarousel-3535:
    title: logos
    attributes:
      enabled: 0
      title: 'Some of <strong>my clients</strong>'
      nav: enable
      slides: '3'
      autoplay: enable
      autoplaySpeed: ''
      items:
        -
          image: 'gantry-media://images/clients/twitter.png'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: Twitter
        -
          image: 'gantry-media://clients/magento.png'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: Magento
        -
          image: 'gantry-media://clients/mailchimp.png'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: MailChimp
        -
          image: 'gantry-media://clients/nexternal.png'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: Nexternal
        -
          image: 'gantry-media://images/clients/wordpress.png'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: Wordpress
        -
          image: 'gantry-media://clients/google.png'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: button-outline
          name: Google
  sectiontitle-2639:
    title: 'Section Title'
    attributes:
      title: 'get in '
      label: touch
      icon: 'fa fa-envelope fa-2x'
    block:
      variations: center
  social-8515:
    attributes:
      display: icons_only
      items:
        -
          icon: 'fa fa-facebook-square fa-fw fa-2x'
          text: facebook
          link: 'http://www.facebook.com/'
          name: Facebook
        -
          icon: 'fa fa-twitter-square fa-fw fa-2x'
          text: twitter
          link: 'http://www.twitter.com/'
          name: Twitter
        -
          icon: 'fa fa-google-plus-square fa-fw fa-2x'
          text: 'google plus'
          link: 'https://plus.google.com/'
          name: Google+
        -
          icon: 'fa fa-linkedin-square fa-fw fa-2x'
          text: linkedin
          link: 'https://ca.linkedin.com/in/leonid-spektor-3a71a94'
          name: LinkedIn
        -
          icon: 'fa fa-pinterest-square fa-fw fa-2x'
          text: pintrest
          link: pintrest.com
          name: Pintrest
        -
          icon: 'fa fa-youtube-play fa-fw fa-2x'
          text: vimeo
          link: vimeo.com
          name: Vimeo
  contactdetails-5862:
    title: 'Contact Details'
    attributes:
      address: '50 Lynn Williams Street, Unit 414,</br> Toronto, Ontario, Canada'
      phone: 416-500-8950
      phone2: ''
      email: deanbalh@gmail.com
      icon: 'fa fa-map-marker fa-2x'
  custom-5538:
    title: 'Custom HTML'
    attributes:
      html: "<h4 class=\"center\">Drop me a Line</h4>\n[contact-form-7 id=\"12\" title=\"Contact form 1\"]"
      filter: '1'
  custom-8220:
    title: 'Custom HTML'
    attributes:
      html: "<div id=\"map_canvas\" class=\"item_fade_in\">\n</div>\n<script src=\"{{ url('gantry-assets://js/gmap-settings.js') }}\"></script>\n<script async defer src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDViAPRqigYG26MGZpXJuBfuuWgsQthfJI&callback=initMap\"\n  type=\"text/javascript\"></script>\n"
      twig: '1'
  copyright-1736:
    block:
      variations: 'nopaddingall nomarginall'
  totop-8670:
    title: 'To Top'
    attributes:
      css:
        class: ''
      icon: 'fa fa-angle-up fa-2x'
      content: ''
    block:
      variations: 'nopaddingall nomarginall'
