ordering:
  home: ''
  about: ''
  experience: ''
  skills: ''
  education: ''
  readings: ''
  testimonials: ''
  contact: ''
items:
  home:
    object_id: 892
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  about:
    object_id: 885
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  experience:
    object_id: 890
  skills:
    object_id: 887
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
  education:
    object_id: 888
  readings:
    object_id: 886
  testimonials:
    object_id: 889
  contact:
    object_id: 891
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
