ordering:
  home: ''
  about: ''
  process: ''
  skills: ''
  resume: ''
  works: ''
  clients: ''
  contact: ''
items:
  home:
    id: 892
    type: custom
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    anchor_class: ''
  about:
    id: 885
    type: custom
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    anchor_class: ''
  process:
    id: 890
    type: custom
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    anchor_class: ''
  skills:
    id: 887
    type: custom
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    anchor_class: ''
  resume:
    id: 888
    type: custom
    enabled: true
    anchor_class: ''
  works:
    id: 886
    type: custom
    enabled: true
    anchor_class: ''
  clients:
    id: 889
    type: custom
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    anchor_class: ''
  contact:
    id: 891
    type: custom
    enabled: '1'
    dropdown_dir: right
    dropdown_hide: '0'
    width: auto
    anchor_class: ''
